<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Post Editor</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Post</li>
            </ol>
        </nav>
    </div>
    <a href="<?= $this->router->to('adminPostEdit', ['id'=>0]) ?>" class="btn btn-primary">Create New</a>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-3">
                <form method="GET" class="card-body">
                    <h5 class="card-title">Search</h5>
                    <?= $form->field('q') ?>
                    <?= $form->field('status') ?>
                    <div class="text-right">
                        <button class="btn btn-primary">Find</button>
                    </div>
                </form>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <div>Total item: <?= number_format($total); ?></div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <?php if($posts): ?>
                <?php $csrf = $form->csrfToken(); ?>
                <ul class="list-group list-group-flush card mb-3">
                    <?php foreach($posts as $post): ?>
                        <?php
                            $plagiarism = false;
                            if (isset($post->plagiarism) && $post->plagiarism->value)
                                $plagiarism = $post->plagiarism;
                        ?>
                        <li class="list-group-item<?= ($plagiarism?' plagiarism':'') ?>">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    <?= $post->title->safe ?>
                                </h5>
                                <div>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Action">
                                        <a href="<?= $this->router->to('adminPostEdit', ['id'=>$post->id]) ?>" class="btn btn-secondary" title="Edit">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <?php if($post->status->value == 3 && isset($post->page)): ?>
                                            <a href="<?= $post->page ?>" class="btn btn-secondary" title="View Page" target="_blank">
                                                <i class="fas fa-external-link-square-alt"></i>
                                            </a>
                                        <?php endif; ?>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <button id="post-action-<?= $post->id ?>" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                            <div class="dropdown-menu" aria-labelledby="post-action-<?= $post->id ?>">
                                                <a class="dropdown-item"
                                                    data-toggle="confirm"
                                                    data-text="Are you sure want to remove this item?"
                                                    data-btn-type="danger"
                                                    href="<?= $this->router->to('adminPostRemove', ['id'=>$post->id], ['noob'=>$csrf]) ?>">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <small>
                                <span title="Created">
                                    <i class="far fa-calendar-plus"></i>
                                    <?= $post->created->format('M d, Y H:i') ?>
                                </span>
                                &middot;
                                <span title="Creator">
                                    <i class="fas fa-user"></i>
                                    <?= $post->user->fullname->safe ?>
                                </span>

                                <?php if($post->status->value == 1): ?>
                                    &middot;
                                    <span title="Status" class="text-warning">
                                        Draft
                                    </span>
                                <?php endif; ?>
                                <?php if($post->status->value == 2): ?>
                                    &middot;
                                    <span title="Status" class="text-primary">
                                        Editor
                                    </span>
                                <?php endif; ?>
                            </small>
                            <?php if($plagiarism): ?>
                                <br>
                                <small>
                                    <i class="fas fa-copyright"></i> <?= $plagiarism->safe ?>
                                </small>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php if($pages): ?>
                <?= $this->partial('shared/pagination', ['pages'=>$pages, 'align'=>'right']); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<style>
.plagiarism {
    overflow: hidden;
}
.plagiarism:before {
    transform: rotate(-45deg);
    content: 'plagiarism';
    position: absolute;
    color: white;
    padding: 0 5px;
    background-color: red;
    font-size: 10px;
    text-align: center;
    width: 100px;
    left: -20px;
    top: 22px;
}
</style>
